# Generated by Django 3.2 on 2021-05-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RemoteComputeAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileTest',
        ),
    ]
